Header and Navbar Completed
kalviumcommunity/IndexGuru pull request #2
Opened 2023-03-07 08:13 UTC by AnjaniKumar1515

2023-03-10 10:06 UTC, aditya-190 requested changes
Please make the required changes before merging the changes.

2023-03-10 10:06 UTC, aditya-190 commented on README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
Please update the README file to add a brief description about your project and you can also add checklist of the tasks that you have done in the project for tracking your progress.

2023-03-10 10:06 UTC, aditya-190 commented on README.old.md
> +
You can remove this file.

2023-03-10 10:06 UTC, aditya-190 commented on package.json
> +    "@testing-library/jest-dom": "^5.16.5",
You can add the testing-libraries in devDependencies.

2023-03-10 10:06 UTC, aditya-190 commented on public/manifest.json
> +  "name": "Create React App Sample",
Add your project name here.

2023-03-10 10:06 UTC, aditya-190 commented on src/Components/Login.js
> +class LoginForm extends React.Component {
In my opinion, It is better to use functional components. Read this to know more -> https://stackoverflow.com/a/57579403

2023-03-10 10:06 UTC, aditya-190 commented on src/Components/Navbar.js
> +    setInterval(() => {
Hey I am not sure why you are using `setInterval`, but if it is required, please also use `clearInterval` in useEffect return. To know more, read this -> https://www.codementor.io/@damianpereira/how-to-use-clearinterval-inside-react-s-useeffect-and-why-it-is-important-1si7mztjlk

2023-03-13 05:21 UTC, aditya-190 approved these changes
Looks Good to me. Pls merge these changes.

2023-03-13 06:41 UTC, merged

2023-04-21 07:19 UTC, AnjaniKumar1515 commented on README.old.md
> +
This file was removed

2023-04-21 07:20 UTC, AnjaniKumar1515 commented on public/manifest.json
> +  "name": "Create React App Sample",
The required changes have been made.